spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinemahub
    username: admin
    password: verysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


app:
  jwtSecret: EhOW5DsaD9/Zw/0k68ulRgTGNEOjToLE8jcfQtDGUK8YvfQpsIXma9uP16mW0Rjh
  jwtExpirationInMs: 36000000

